name: GitHub - Activity Update Readme.md

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v0.1.8

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}